site_name: Tab Docs
pages:
    - Home: index.md
    - Artists: artists.md
    - Exercises: exercises.md
theme: 'material'
extra_css:
  - 'https://raw.githubusercontent.com/0xfe/vextab/master/releases/vextab.css'
extra_javascript:
  - 'https://raw.githubusercontent.com/0xfe/vextab/master/releases/vextab-div.js'
