site_name: Tab Docs
pages:
    - Home: index.md
    - Artists: artists.md
    - Exercises: exercises.md
theme: 'material'
extra_css:
  - 'stylesheets/vextab.css'
extra_javascript:
  - 'javascripts/vextab-div.js'
  - 'javascripts/vextab-fretboard.js'